import handlers.personal_actions.commands.balance
import handlers.personal_actions.commands.help
import handlers.personal_actions.commands.lang
import handlers.personal_actions.commands.rules
import handlers.personal_actions.commands.settings
import handlers.personal_actions.commands.start
import handlers.personal_actions.commands.statistics
import handlers.personal_actions.commands.share