version: '3'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    container_name: blackjack_bot
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    build: 
      context: .
      dockerfile: db/Dockerfile
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: bjdb
    ports:
      - 5431:5432
    container_name: blackjack_bot_db