version: '3'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    container_name: bj-app
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    build: 
      context: .
      dockerfile: db/Dockerfile
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5431:5432
    container_name: bj-postgres